// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";
import { EnvConfig } from "./src/config/env";

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
		seed: "tsx prisma/seeds/index.ts",
	},
	datasource: {
		url: EnvConfig.DATABASE_URL,
	},
});
