import type { PrismaClient } from "../../src/generated/prisma/client";

const languages = [
	// Most spoken / most relevant for a mentoring platform
	{ name: "English", code: "en" },
	{ name: "Mandarin Chinese", code: "zh" },
	{ name: "Hindi", code: "hi" },
	{ name: "Spanish", code: "es" },
	{ name: "Arabic", code: "ar" },
	{ name: "French", code: "fr" },
	{ name: "Bengali", code: "bn" },
	{ name: "Portuguese", code: "pt" },
	{ name: "Russian", code: "ru" },
	{ name: "Urdu", code: "ur" },
	{ name: "Indonesian", code: "id" },
	{ name: "German", code: "de" },
	{ name: "Japanese", code: "ja" },
	{ name: "Swahili", code: "sw" },
	{ name: "Marathi", code: "mr" },
	{ name: "Telugu", code: "te" },
	{ name: "Turkish", code: "tr" },
	{ name: "Tamil", code: "ta" },
	{ name: "Vietnamese", code: "vi" },
	{ name: "Korean", code: "ko" },
	{ name: "Italian", code: "it" },
	{ name: "Hausa", code: "ha" },
	{ name: "Thai", code: "th" },
	{ name: "Gujarati", code: "gu" },
	{ name: "Kannada", code: "kn" },
	{ name: "Polish", code: "pl" },
	{ name: "Malayalam", code: "ml" },
	{ name: "Punjabi", code: "pa" },
	{ name: "Dutch", code: "nl" },
	{ name: "Romanian", code: "ro" },
	{ name: "Ukrainian", code: "uk" },
	{ name: "Greek", code: "el" },
	{ name: "Czech", code: "cs" },
	{ name: "Swedish", code: "sv" },
	{ name: "Hungarian", code: "hu" },
	{ name: "Hebrew", code: "he" },
	{ name: "Danish", code: "da" },
	{ name: "Finnish", code: "fi" },
	{ name: "Norwegian", code: "no" },
	{ name: "Persian", code: "fa" },
	{ name: "Malay", code: "ms" },
	{ name: "Afrikaans", code: "af" },
	{ name: "Filipino", code: "tl" },
	{ name: "Serbian", code: "sr" },
	{ name: "Croatian", code: "hr" },
	{ name: "Slovak", code: "sk" },
	{ name: "Bulgarian", code: "bg" },
	{ name: "Catalan", code: "ca" },
	{ name: "Lithuanian", code: "lt" },
	{ name: "Latvian", code: "lv" },
];

export async function seedLanguages(prisma: PrismaClient) {
	await prisma.skill.createMany({
		data: languages,
		skipDuplicates: true,
	});
}
