import type { PrismaClient } from "../../src/generated/prisma/client";

// ~800 curated skills across all your domains
const skills = [
	// ─── Software Engineering ───────────────────────────────────────────────
	{ name: "Data Structures" },
	{ name: "Algorithms" },
	{ name: "Object-Oriented Programming" },
	{ name: "Functional Programming" },
	{ name: "Design Patterns" },
	{ name: "System Design" },
	{ name: "Clean Code" },
	{ name: "Code Review" },
	{ name: "Debugging" },
	{ name: "Unit Testing" },
	{ name: "Integration Testing" },
	{ name: "Test-Driven Development" },
	{ name: "Agile Methodology" },
	{ name: "Scrum" },
	{ name: "Kanban" },
	{ name: "Git" },
	{ name: "GitHub" },
	{ name: "GitLab" },
	{ name: "Bitbucket" },
	{ name: "REST API Design" },
	{ name: "GraphQL" },
	{ name: "gRPC" },
	{ name: "WebSockets" },
	{ name: "Microservices Architecture" },
	{ name: "Monolithic Architecture" },
	{ name: "Event-Driven Architecture" },
	{ name: "Domain-Driven Design" },
	{ name: "SOLID Principles" },
	{ name: "Refactoring" },
	{ name: "Documentation Writing" },
	{ name: "Technical Writing" },
	{ name: "Open Source Contribution" },
	{ name: "API Integration" },
	{ name: "Webhooks" },
	{ name: "OAuth 2.0" },
	{ name: "JWT" },
	{ name: "Software Architecture" },

	// ─── Frontend Development ────────────────────────────────────────────────
	{ name: "HTML" },
	{ name: "CSS" },
	{ name: "JavaScript" },
	{ name: "TypeScript" },
	{ name: "React" },
	{ name: "Next.js" },
	{ name: "Vue.js" },
	{ name: "Nuxt.js" },
	{ name: "Angular" },
	{ name: "Svelte" },
	{ name: "SvelteKit" },
	{ name: "Tailwind CSS" },
	{ name: "Bootstrap" },
	{ name: "Sass / SCSS" },
	{ name: "CSS Modules" },
	{ name: "Styled Components" },
	{ name: "Framer Motion" },
	{ name: "GSAP" },
	{ name: "Webpack" },
	{ name: "Vite" },
	{ name: "Babel" },
	{ name: "ESLint" },
	{ name: "Prettier" },
	{ name: "Jest" },
	{ name: "Cypress" },
	{ name: "Playwright" },
	{ name: "Storybook" },
	{ name: "Web Accessibility (WCAG)" },
	{ name: "Responsive Design" },
	{ name: "Progressive Web Apps" },
	{ name: "Web Performance Optimization" },
	{ name: "Browser DevTools" },
	{ name: "React Query" },
	{ name: "Redux" },
	{ name: "Zustand" },
	{ name: "MobX" },
	{ name: "Web Components" },
	{ name: "Three.js" },
	{ name: "D3.js" },
	{ name: "Chart.js" },
	{ name: "SEO Optimization" },
	{ name: "Internationalization (i18n)" },

	// ─── Backend Development ─────────────────────────────────────────────────
	{ name: "Node.js" },
	{ name: "Express.js" },
	{ name: "NestJS" },
	{ name: "Fastify" },
	{ name: "Python" },
	{ name: "Django" },
	{ name: "FastAPI" },
	{ name: "Flask" },
	{ name: "Ruby on Rails" },
	{ name: "Java" },
	{ name: "Spring Boot" },
	{ name: "Kotlin" },
	{ name: "Go" },
	{ name: "Rust" },
	{ name: "PHP" },
	{ name: "Laravel" },
	{ name: "C#" },
	{ name: ".NET" },
	{ name: "ASP.NET Core" },
	{ name: "PostgreSQL" },
	{ name: "MySQL" },
	{ name: "SQLite" },
	{ name: "MongoDB" },
	{ name: "Redis" },
	{ name: "Elasticsearch" },
	{ name: "Cassandra" },
	{ name: "DynamoDB" },
	{ name: "Prisma ORM" },
	{ name: "TypeORM" },
	{ name: "Sequelize" },
	{ name: "Mongoose" },
	{ name: "SQL" },
	{ name: "Database Design" },
	{ name: "Database Indexing" },
	{ name: "Query Optimization" },
	{ name: "Message Queues" },
	{ name: "RabbitMQ" },
	{ name: "Apache Kafka" },
	{ name: "Caching Strategies" },
	{ name: "Background Jobs" },
	{ name: "Server-Sent Events" },
	{ name: "API Rate Limiting" },
	{ name: "Load Balancing" },

	// ─── Mobile Development ──────────────────────────────────────────────────
	{ name: "React Native" },
	{ name: "Flutter" },
	{ name: "Dart" },
	{ name: "Swift" },
	{ name: "SwiftUI" },
	{ name: "Objective-C" },
	{ name: "iOS Development" },
	{ name: "Android Development" },
	{ name: "Jetpack Compose" },
	{ name: "Expo" },
	{ name: "Mobile UI Design" },
	{ name: "Push Notifications" },
	{ name: "App Store Optimization" },
	{ name: "Mobile Performance Optimization" },
	{ name: "Offline-First Development" },
	{ name: "Deep Linking" },
	{ name: "In-App Purchases" },
	{ name: "Firebase" },
	{ name: "Mobile Testing" },
	{ name: "Xcode" },
	{ name: "Android Studio" },

	// ─── DevOps & Cloud ──────────────────────────────────────────────────────
	{ name: "Docker" },
	{ name: "Kubernetes" },
	{ name: "AWS" },
	{ name: "Google Cloud Platform" },
	{ name: "Microsoft Azure" },
	{ name: "Terraform" },
	{ name: "Ansible" },
	{ name: "CI/CD Pipelines" },
	{ name: "GitHub Actions" },
	{ name: "Jenkins" },
	{ name: "CircleCI" },
	{ name: "Linux" },
	{ name: "Bash Scripting" },
	{ name: "Nginx" },
	{ name: "Apache" },
	{ name: "Prometheus" },
	{ name: "Grafana" },
	{ name: "ELK Stack" },
	{ name: "Datadog" },
	{ name: "Infrastructure as Code" },
	{ name: "Serverless" },
	{ name: "AWS Lambda" },
	{ name: "AWS S3" },
	{ name: "AWS EC2" },
	{ name: "AWS RDS" },
	{ name: "Cloudflare" },
	{ name: "Networking Fundamentals" },
	{ name: "DNS Management" },
	{ name: "SSL/TLS" },
	{ name: "Helm" },
	{ name: "ArgoCD" },
	{ name: "Site Reliability Engineering" },
	{ name: "Incident Management" },

	// ─── Data Science & Analytics ────────────────────────────────────────────
	{ name: "Python for Data Science" },
	{ name: "R" },
	{ name: "Pandas" },
	{ name: "NumPy" },
	{ name: "Data Cleaning" },
	{ name: "Exploratory Data Analysis" },
	{ name: "Data Visualization" },
	{ name: "Matplotlib" },
	{ name: "Seaborn" },
	{ name: "Tableau" },
	{ name: "Power BI" },
	{ name: "Looker" },
	{ name: "Google Analytics" },
	{ name: "Excel for Data Analysis" },
	{ name: "Statistical Analysis" },
	{ name: "Hypothesis Testing" },
	{ name: "A/B Testing" },
	{ name: "SQL for Analytics" },
	{ name: "BigQuery" },
	{ name: "Snowflake" },
	{ name: "dbt" },
	{ name: "Apache Spark" },
	{ name: "Data Warehousing" },
	{ name: "ETL Pipelines" },
	{ name: "Business Intelligence" },
	{ name: "KPI Definition" },
	{ name: "Cohort Analysis" },
	{ name: "Funnel Analysis" },
	{ name: "Data Storytelling" },
	{ name: "Jupyter Notebooks" },

	// ─── Machine Learning & AI ───────────────────────────────────────────────
	{ name: "Machine Learning" },
	{ name: "Deep Learning" },
	{ name: "Neural Networks" },
	{ name: "Natural Language Processing" },
	{ name: "Computer Vision" },
	{ name: "Scikit-learn" },
	{ name: "TensorFlow" },
	{ name: "PyTorch" },
	{ name: "Keras" },
	{ name: "Hugging Face" },
	{ name: "Large Language Models" },
	{ name: "Prompt Engineering" },
	{ name: "Retrieval-Augmented Generation" },
	{ name: "Fine-tuning LLMs" },
	{ name: "OpenAI API" },
	{ name: "LangChain" },
	{ name: "Vector Databases" },
	{ name: "Pinecone" },
	{ name: "Feature Engineering" },
	{ name: "Model Evaluation" },
	{ name: "Model Deployment" },
	{ name: "MLOps" },
	{ name: "Reinforcement Learning" },
	{ name: "Recommendation Systems" },
	{ name: "Time Series Analysis" },
	{ name: "Data Labeling" },
	{ name: "AI Ethics" },
	{ name: "Generative AI" },

	// ─── Cybersecurity ───────────────────────────────────────────────────────
	{ name: "Network Security" },
	{ name: "Application Security" },
	{ name: "Penetration Testing" },
	{ name: "Ethical Hacking" },
	{ name: "Vulnerability Assessment" },
	{ name: "OWASP Top 10" },
	{ name: "Cryptography" },
	{ name: "Threat Modeling" },
	{ name: "Security Auditing" },
	{ name: "Identity & Access Management" },
	{ name: "Zero Trust Security" },
	{ name: "SIEM Tools" },
	{ name: "Incident Response" },
	{ name: "Malware Analysis" },
	{ name: "Reverse Engineering" },
	{ name: "Cloud Security" },
	{ name: "DevSecOps" },
	{ name: "SOC Operations" },
	{ name: "Compliance (ISO 27001)" },
	{ name: "GDPR Compliance" },
	{ name: "Firewall Management" },
	{ name: "Burp Suite" },
	{ name: "Metasploit" },
	{ name: "Wireshark" },

	// ─── Product Management ──────────────────────────────────────────────────
	{ name: "Product Strategy" },
	{ name: "Product Roadmapping" },
	{ name: "User Story Writing" },
	{ name: "Backlog Grooming" },
	{ name: "Prioritization Frameworks" },
	{ name: "OKRs" },
	{ name: "Market Research" },
	{ name: "Competitive Analysis" },
	{ name: "User Interviews" },
	{ name: "Jobs-to-be-Done Framework" },
	{ name: "Product Analytics" },
	{ name: "Feature Flagging" },
	{ name: "Go-to-Market Strategy" },
	{ name: "Stakeholder Management" },
	{ name: "Cross-functional Collaboration" },
	{ name: "Sprint Planning" },
	{ name: "Product Discovery" },
	{ name: "Metrics & KPIs" },
	{ name: "Customer Journey Mapping" },
	{ name: "North Star Metric" },
	{ name: "Jira" },
	{ name: "Confluence" },
	{ name: "Notion" },
	{ name: "Linear" },
	{ name: "Product-Led Growth" },

	// ─── UI/UX Design ────────────────────────────────────────────────────────
	{ name: "Figma" },
	{ name: "Sketch" },
	{ name: "Adobe XD" },
	{ name: "Prototyping" },
	{ name: "Wireframing" },
	{ name: "User Research" },
	{ name: "Usability Testing" },
	{ name: "Information Architecture" },
	{ name: "Interaction Design" },
	{ name: "Visual Design" },
	{ name: "Design Systems" },
	{ name: "Component Libraries" },
	{ name: "Typography" },
	{ name: "Color Theory" },
	{ name: "Gestalt Principles" },
	{ name: "Accessibility Design" },
	{ name: "Mobile-First Design" },
	{ name: "User-Centered Design" },
	{ name: "Design Thinking" },
	{ name: "Heuristic Evaluation" },
	{ name: "A/B Testing for UX" },
	{ name: "Eye Tracking Research" },
	{ name: "Motion Design" },
	{ name: "Micro-interactions" },
	{ name: "InVision" },
	{ name: "Zeplin" },

	// ─── Graphic Design ──────────────────────────────────────────────────────
	{ name: "Adobe Photoshop" },
	{ name: "Adobe Illustrator" },
	{ name: "Adobe InDesign" },
	{ name: "Adobe After Effects" },
	{ name: "Adobe Premiere Pro" },
	{ name: "Canva" },
	{ name: "Brand Identity Design" },
	{ name: "Logo Design" },
	{ name: "Print Design" },
	{ name: "Packaging Design" },
	{ name: "Icon Design" },
	{ name: "Illustration" },
	{ name: "Photo Editing" },
	{ name: "Photo Retouching" },
	{ name: "Layout Design" },
	{ name: "Grid Systems" },
	{ name: "Poster Design" },
	{ name: "Social Media Design" },
	{ name: "Infographic Design" },
	{ name: "3D Design" },
	{ name: "Blender" },

	// ─── Marketing & Growth ──────────────────────────────────────────────────
	{ name: "Digital Marketing" },
	{ name: "Content Marketing" },
	{ name: "Search Engine Optimization" },
	{ name: "Search Engine Marketing" },
	{ name: "Google Ads" },
	{ name: "Meta Ads" },
	{ name: "Email Marketing" },
	{ name: "Marketing Automation" },
	{ name: "Social Media Marketing" },
	{ name: "Influencer Marketing" },
	{ name: "Affiliate Marketing" },
	{ name: "Growth Hacking" },
	{ name: "Conversion Rate Optimization" },
	{ name: "Landing Page Optimization" },
	{ name: "HubSpot" },
	{ name: "Mailchimp" },
	{ name: "Klaviyo" },
	{ name: "Brand Strategy" },
	{ name: "Community Building" },
	{ name: "Product Marketing" },
	{ name: "Campaign Management" },
	{ name: "Market Segmentation" },
	{ name: "Customer Retention" },
	{ name: "Funnel Optimization" },
	{ name: "Copywriting" },
	{ name: "PR & Communications" },

	// ─── Sales ───────────────────────────────────────────────────────────────
	{ name: "B2B Sales" },
	{ name: "B2C Sales" },
	{ name: "SaaS Sales" },
	{ name: "Enterprise Sales" },
	{ name: "Sales Development" },
	{ name: "Prospecting" },
	{ name: "Lead Generation" },
	{ name: "Cold Outreach" },
	{ name: "Cold Calling" },
	{ name: "Sales Negotiation" },
	{ name: "Closing Techniques" },
	{ name: "Account Management" },
	{ name: "Customer Success" },
	{ name: "CRM Management" },
	{ name: "Salesforce" },
	{ name: "HubSpot CRM" },
	{ name: "Pipeline Management" },
	{ name: "Sales Forecasting" },
	{ name: "Demo Presentation" },
	{ name: "Solution Selling" },
	{ name: "Consultative Selling" },
	{ name: "Objection Handling" },
	{ name: "Upselling & Cross-selling" },
	{ name: "Partnership Development" },

	// ─── HR & People Operations ──────────────────────────────────────────────
	{ name: "Talent Acquisition" },
	{ name: "Recruitment" },
	{ name: "Technical Recruiting" },
	{ name: "Onboarding" },
	{ name: "Employee Engagement" },
	{ name: "Performance Management" },
	{ name: "Learning & Development" },
	{ name: "Compensation & Benefits" },
	{ name: "HR Policy Writing" },
	{ name: "Labor Law" },
	{ name: "Conflict Resolution" },
	{ name: "Organizational Design" },
	{ name: "Succession Planning" },
	{ name: "Diversity & Inclusion" },
	{ name: "Culture Building" },
	{ name: "Employee Relations" },
	{ name: "HR Analytics" },
	{ name: "Payroll Management" },
	{ name: "Workday HCM" },
	{ name: "BambooHR" },
	{ name: "Workforce Planning" },
	{ name: "Interview Techniques" },
	{ name: "Job Description Writing" },
	{ name: "Employer Branding" },

	// ─── Finance & Accounting ────────────────────────────────────────────────
	{ name: "Financial Modeling" },
	{ name: "Financial Analysis" },
	{ name: "Budgeting & Forecasting" },
	{ name: "Cash Flow Management" },
	{ name: "Financial Reporting" },
	{ name: "Management Accounting" },
	{ name: "Tax Planning" },
	{ name: "Auditing" },
	{ name: "IFRS" },
	{ name: "GAAP" },
	{ name: "Bookkeeping" },
	{ name: "Accounts Payable" },
	{ name: "Accounts Receivable" },
	{ name: "Payroll Accounting" },
	{ name: "QuickBooks" },
	{ name: "Xero" },
	{ name: "SAP Finance" },
	{ name: "Excel Financial Modeling" },
	{ name: "Valuation" },
	{ name: "Investment Analysis" },
	{ name: "Risk Management" },
	{ name: "Corporate Finance" },
	{ name: "Venture Capital" },
	{ name: "Private Equity" },
	{ name: "Mergers & Acquisitions" },
	{ name: "Fundraising" },

	// ─── Business Strategy ───────────────────────────────────────────────────
	{ name: "Business Strategy" },
	{ name: "Strategic Planning" },
	{ name: "Business Model Design" },
	{ name: "SWOT Analysis" },
	{ name: "OKR Setting" },
	{ name: "Change Management" },
	{ name: "Operations Management" },
	{ name: "Process Improvement" },
	{ name: "Six Sigma" },
	{ name: "Lean Management" },
	{ name: "Supply Chain Management" },
	{ name: "Project Management" },
	{ name: "PMP Certification" },
	{ name: "Executive Communication" },
	{ name: "Board Reporting" },
	{ name: "Business Development" },
	{ name: "Partnership Strategy" },
	{ name: "Corporate Governance" },
	{ name: "Management Consulting" },
	{ name: "Decision Making" },
	{ name: "Data-Driven Decision Making" },

	// ─── Entrepreneurship & Startups ─────────────────────────────────────────
	{ name: "Startup Strategy" },
	{ name: "MVP Development" },
	{ name: "Product-Market Fit" },
	{ name: "Pitch Deck Creation" },
	{ name: "Investor Relations" },
	{ name: "Angel Investing" },
	{ name: "Startup Fundraising" },
	{ name: "Lean Startup Methodology" },
	{ name: "Customer Discovery" },
	{ name: "Business Plan Writing" },
	{ name: "Growth Strategy" },
	{ name: "Team Building" },
	{ name: "Founder Leadership" },
	{ name: "Bootstrapping" },
	{ name: "Equity & Cap Table Management" },
	{ name: "Term Sheet Negotiation" },
	{ name: "Scaling Operations" },
	{ name: "Exit Strategy" },

	// ─── Legal ───────────────────────────────────────────────────────────────
	{ name: "Contract Drafting" },
	{ name: "Contract Review" },
	{ name: "Corporate Law" },
	{ name: "Employment Law" },
	{ name: "Intellectual Property Law" },
	{ name: "Trademark Registration" },
	{ name: "Patent Law" },
	{ name: "Privacy Law" },
	{ name: "GDPR" },
	{ name: "Legal Research" },
	{ name: "Litigation" },
	{ name: "Dispute Resolution" },
	{ name: "Regulatory Compliance" },
	{ name: "Due Diligence" },
	{ name: "Terms of Service Writing" },
	{ name: "Privacy Policy Writing" },
	{ name: "SaaS Legal Agreements" },
	{ name: "Startup Legal Structuring" },
	{ name: "Data Protection" },

	// ─── Content & Copywriting ───────────────────────────────────────────────
	{ name: "Blog Writing" },
	{ name: "Long-form Content Writing" },
	{ name: "SEO Writing" },
	{ name: "UX Writing" },
	{ name: "Technical Copywriting" },
	{ name: "Email Copywriting" },
	{ name: "Ad Copywriting" },
	{ name: "Social Media Writing" },
	{ name: "Ghostwriting" },
	{ name: "Editing & Proofreading" },
	{ name: "Storytelling" },
	{ name: "Brand Voice Development" },
	{ name: "Newsletter Writing" },
	{ name: "Scriptwriting" },
	{ name: "Case Study Writing" },
	{ name: "White Paper Writing" },
	{ name: "Content Strategy" },
	{ name: "Content Calendar Management" },
	{ name: "Thought Leadership Writing" },

	// ─── Video & Film Production ─────────────────────────────────────────────
	{ name: "Video Production" },
	{ name: "Video Editing" },
	{ name: "Cinematography" },
	{ name: "Screenwriting" },
	{ name: "Storyboarding" },
	{ name: "Color Grading" },
	{ name: "Sound Design" },
	{ name: "Motion Graphics" },
	{ name: "YouTube Content Creation" },
	{ name: "Short-form Video (Reels/TikTok)" },
	{ name: "Documentary Filmmaking" },
	{ name: "Live Streaming" },
	{ name: "Podcast Production" },
	{ name: "Voiceover" },
	{ name: "DaVinci Resolve" },
	{ name: "Final Cut Pro" },
	{ name: "Adobe Premiere Pro" },
	{ name: "Drone Videography" },

	// ─── Cross-domain Soft Skills ────────────────────────────────────────────
	{ name: "Public Speaking" },
	{ name: "Presentation Skills" },
	{ name: "Communication Skills" },
	{ name: "Active Listening" },
	{ name: "Written Communication" },
	{ name: "Critical Thinking" },
	{ name: "Problem Solving" },
	{ name: "Analytical Thinking" },
	{ name: "Time Management" },
	{ name: "Project Planning" },
	{ name: "Leadership" },
	{ name: "Team Leadership" },
	{ name: "Mentoring" },
	{ name: "Coaching" },
	{ name: "Negotiation" },
	{ name: "Facilitation" },
	{ name: "Workshop Design" },
	{ name: "Emotional Intelligence" },
	{ name: "Adaptability" },
	{ name: "Creativity" },
	{ name: "Innovation" },
	{ name: "Remote Work" },
	{ name: "Async Communication" },
	{ name: "Cross-cultural Communication" },
	{ name: "Networking" },
	{ name: "Personal Branding" },
	{ name: "Self-Management" },
	{ name: "Research Skills" },
];

export async function seedSkills(prisma: PrismaClient) {
	await prisma.skill.createMany({
		data: skills,
		skipDuplicates: true,
	});
}
