export const TYPES = {
	// cache
	CacheService: Symbol.for("CacheService"),

	//repository
	UserRepository: Symbol.for("UserRepository"),
	TokenRepository: Symbol.for("TokenRepository"),
	PrismaTokenRepository: Symbol.for("PrismaTokenRepository"),
	MentorRepository: Symbol.for("MentorRepository"),
	EducationRepository: Symbol.for("EducationRepository"),
	ExperienceRepository: Symbol.for("ExperienceRepository"),
	AchievementRepository: Symbol.for("AchievementRepository"),
	SkillRepository: Symbol.for("SkillRepository"),
	MentorSkillRepository: Symbol.for("MentorSkillRepository"),
	MentorLanguageRepository: Symbol.for("MentorLanguageRepository"),
	LanguageRepository: Symbol.for("LanguageRepository"),
	DomainRepository: Symbol.for("DomainRepository"),
	SocaiLinkRepository: Symbol.for("SocaiLinkRepository"),
	MentorBookingRulesRepository: Symbol.for("MentorBookingRulesRepository"),
	SessionRepository: Symbol.for("SessionRepository"),
	//services
	EmailService: Symbol.for("EmailService"),
	HashService: Symbol.for("HashService"),
	TokenService: Symbol.for("TokenService"),
	S3Service: Symbol.for("S3Service"),

	//queries
	MentorQuery: Symbol.for("MentorQuery"),
	// usecases
	ForgetPasswordUseCase: Symbol.for("ForgetPasswordUseCase"),
	LoginUseCase: Symbol.for("LoginUseCase"),
	RefreshTokenUseCase: Symbol.for("RefreshTokenUseCase"),
	ResetPasswordUseCase: Symbol.for("ResetPasswordUseCase"),
	SignUpUseCase: Symbol.for("SignUpUseCase"),
	VerifyEmailUseCase: Symbol.for("VerifyEmailUseCase"),
	GetUserUsecase: Symbol.for("GetUserUsecase"),
	UpdateBlockStatus: Symbol.for("UpdateBlockStatus"),
	UserUploadUrlUsecase: Symbol.for("UserUploadUrlUsecase"),
	OAuthUseCase: Symbol.for("OAuthUseCase"),
	PassPortConfig: Symbol.for("PassPortConfig"),
	VerifyMentorUsecase: Symbol.for("VerifyMentorUsecase"),
	AddEducationUsecase: Symbol.for("AddEducationUsecase"),
	EditEducationUsecase: Symbol.for("EditEducationUsecase"),
	DeleteEducationUsecase: Symbol.for("DeleteEducationUsecase"),
	AddExperienceUsecase: Symbol.for("AddExperienceUsecase"),
	EditExperienceUsecase: Symbol.for("EditExperienceUsecase"),
	DeleteExperienceUsecase: Symbol.for("DeleteExperienceUsecase"),
	AddAchievementUsecase: Symbol.for("AddAchievementUsecase"),
	GetSkillUsecase: Symbol.for("GetSkillUsecase"),
	GetMentorProfileUsecase: Symbol.for("GetMentorProfileUsecase"),
	AddMentorSkillUsecase: Symbol.for("AddMentorSkillUsecase"),
	DeleteMentorSkillUsecase: Symbol.for("DeleteMentorSkillUsecase"),
	AddMentorLanguageUsecase: Symbol.for("AddMentorLanguageUsecase"),
	DeleteMentorLanguageUsecase: Symbol.for("DeleteMentorLanguageUsecase"),
	GetLanguageUsecase: Symbol.for("GetLanguageUsecase"),
	EditUserProfileUsecase: Symbol.for("EditUserProfileUsecase"),
	GetDomainUsecase: Symbol.for("GetDomainUsecase"),
	UpdateMentorOverviewUsecase: Symbol.for("UpdateMentorOverviewUsecase"),
	CreateSocialLinksUsecse: Symbol.for("CreateSocialLinksUsecse"),
	UpdateMentorBookingRulesUsecase: Symbol.for(
		"UpdateMentorBookingRulesUsecase",
	),
	MentorStatusUpdateUsecase: Symbol.for("MentorStatusUpdateUsecase"),
	ChangePasswordUsecase: Symbol.for("ChangePasswordUsecase"),
	AddSessionUsecase: Symbol.for("AddSessionUsecase"),
	EditSessionUsecase: Symbol.for("EditSessionUsecase"),
	DeleteSessionUsecase: Symbol.for("DeleteSessionUsecase"),
	ToggleSessionVisibilityUsecase: Symbol.for("ToggleSessionVisibilityUsecase"),
	GetSessionUsecase: Symbol.for("GetSessionUsecase"),
	UserUpdateProfileKeyUsecase: Symbol.for("UserUpdateProfileKeyUsecase"),
	//controller
	AuthController: Symbol.for("AuthController"),
	UserManagementController: Symbol.for("UserManagementController"),
	AdminLoginUseCase: Symbol.for("AdminLoginUseCase"),
	ProfileMentorController: Symbol.for("ProfileMentorController"),
	SettingController: Symbol.for("SettingController"),
	SessionController: Symbol.for("SessionController"),
	// Infrastructure Clients
	PrismaClient: Symbol.for("PrismaClient"),
	RedisClient: Symbol.for("RedisClient"),
} as const;
