name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  code-quality:
    name: code quality checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Verify Branch Naming Convention
        run: |
          BRANCH_NAME="${{ github.head_ref }}"

          REGEX="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|release|hotfix)\/[a-z0-9-]+$"

          echo "Checking branch: $BRANCH_NAME"

          if [[ ! $BRANCH_NAME =~ $REGEX ]]; then
            echo "::error::Branch name '$BRANCH_NAME' does not follow the convention."
            echo "Expected format: type/description (e.g., feat/admin-dashboard)"
            echo "Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, release, hotfix"
            exit 1
          fi
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Conventional Commits (Individual Commits)
        uses: wagoid/commitlint-github-action@v6

      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - run: pnpm prisma generate
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/user_service?schema=public"

      - run: pnpm run lint

      - run: pnpm run build
